#!/bin/bash
# **********************************************************************
# Ericsson Radio Systems AB                                     SCRIPT
# **********************************************************************
#
# (c) Ericsson Radio Systems AB 2016 - All rights reserved.
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Radio Systems AB, Sweden. The programs may be used and/or
# copied only with the written permission from Ericsson Radio Systems AB
# or in accordance with the terms and conditions stipulated in the
# agreement/contract under which the program(s) have been supplied.
#
# **********************************************************************
#   Command Section
#
# **********************************************************************
#
#   Main body of program
#
# ********************************************************************
#
echo "CONTAINER_IP=$IP"
echo "deployMode=$deployMode"
echo "SchemaRegistry=$schemaRegistry"
echo "flowPath=$flowPath"

#Execute Spark submit command with following arguments
spark-submit --class $mainClass --deploy-mode $deployMode --conf spark.executor.extraJavaOptions=$schemaRegistry --conf spark.driver.extraJavaOptions=$schemaRegistry --master $masterUrl $bpsstreamningJar $flowPath $jobArguments
tail -f /dev/null
